name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create directories
      run: mkdir -p bin obj

    - name: Build source
      run: make src

    - name: Build tests
      run: make tests

    - name: Run tests
      run: make runtest
